services:

  # Наш сервис называется "web"
  web:
    # build: . означает "собери образ из Dockerfile
    # который лежит в текущей папке"
    build: .
    container_name: simple-sidebar

    ports:
      # Левая часть — порт на твоём компьютере (можешь изменить)
      # Правая часть — порт внутри контейнера (Nginx слушает 80)
      # Итог: открываешь localhost:8080 → попадаешь на Nginx внутри контейнера
      - "8080:80"

    # Перезапускать контейнер автоматически если он упал
    restart: unless-stopped